### ISSUE TITLE
Upload to OpenVSX

### ISSUE THREAD

**Issue by ignitedPotato** [devMikeUA/vscode_mikrotik_routeros_script#4]
Could you provide the extension on https://open-vsx.org/?
This way not only Visual Studio Code can benefit from your extension.

Thank you

**Comment by devMikeUA** [comment]
I'll think about this. Thank you

**Comment by devMikeUA** [comment]
Here we go =)
https://open-vsx.org/extension/devMikeUA/mikrotik-routeros-script
